resources:
- name: repo
  type: git
  check_every: 1m
  source:
    uri: https://github.com/diwakar-k/test
    branch: main
- name: storage
  type: s3
  source:
      # Name of the bucket in S3 account
    bucket: rishi-demo
    regexp: jars/springboot-concourse-(.*)-SNAPSHOT.jar
    # versioned_file: repo/(*).txt
    region_name: ap-south-1
      # filename of the application to read/write in S3 (check S3 resource documentation for parameters) 
      # AWS Credentials are passed in command line on set-pipeline. Concourse can also use an external vault system to store credentials
    access_key_id: {{aws-access-key}}
    secret_access_key: {{aws-secret-key}}

jobs:
- name: test-and-build
  public: true
  plan:
    - get: repo
      trigger: true
    - get: storage
    - task: run-test-and-build-jar-file
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: java
            tag: 8
        inputs:
        - name: repo
        outputs:
        - name: jar-file
        caches:
        - path: repo/.m2
        run:
          path: ./repo/update.sh
    - put: storage
      params:
        file: jar-file/*.jar
# jobs:
#   - name: testjob
#     plan:
#     - get: repo
#       trigger: true
#     - task: sample
#       config:
#           platform: linux
#           image_resource:
#             type: registry-image
#             source:
#               repository: ubuntu
#           inputs:
#             - name: repo
#           run:
#             path: sh
#             args:
#               - bash
#               - -ceux
#               - sh repo/update.sh
#     - put: storage
#       params:
#         file: repo/*.txt
#         # acl: public-read